# Extract and Transform 2025 NYC Yellow Taxi Data

## Extract

In [10]:
import polars as pl

In [11]:
df = pl.scan_parquet("*.parquet")

## Transform

In [12]:
df = df.with_columns(replaced=pl.col("payment_type").replace_strict([0, 1, 2, 3, 4, 5, 6], 
["FlexFareTrip", "CreditCard", "Cash", "NoCharge", "Dispute","Unknown","VoidedTrip"])
).drop("payment_type"
).rename({"replaced": "payment_type"})

df = df.with_columns(replaced=pl.col("RatecodeID").replace_strict([1, 2, 3, 4, 5, 6, 99], 
["StandardRate", "JFK", "Newark", "NassauOrWestchester", "NegotiatedFare", "GroupRide", "NullUnknown"])
).drop("RatecodeID"
).rename({"replaced": "RateCode"})

df = df.drop_nulls()

In [13]:
df.sink_csv("2025_yellow_cab_data.csv")

## Explore one file to create a PostgreSQL table

In [5]:
df = pl.read_parquet("yellow_tripdata_2025-06.parquet")

In [6]:
df.head()

shape: (5, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ total_amo ┆ congestio ┆ Airport_f ┆ cbd_conge │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ unt       ┆ n_surchar ┆ ee        ┆ stion_fee │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ge        ┆ ---       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆ f64       ┆           ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2025-06-0 ┆ 2025-06-0 ┆ 1         ┆ … ┆ 87.39     ┆ 2.5       ┆ 1.75      ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:02:50  ┆ 00:39:51  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-06-0 ┆ 2025-06-0 ┆ 1         ┆ … ┆ 36.54     ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:11:27  ┆ 00:35:35  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2025-06-0 ┆ 2025-06-0 ┆ 0         ┆ … ┆ 15.54     ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:43:47  ┆ 00:49:16  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2025-06-0 ┆ 2025-06-0 ┆ 1         ┆ … ┆ 79.75     ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:01:15  ┆ 00:42:16  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 7        ┆ 2025-06-0 ┆ 2025-06-0 ┆ 1         ┆ … ┆ 31.5      ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:16:32  ┆ 00:16:32  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
df.null_count()

shape: (1, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ total_amo ┆ congestio ┆ Airport_f ┆ cbd_conge │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ unt       ┆ n_surchar ┆ ee        ┆ stion_fee │
│ u32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ge        ┆ ---       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ u32       ┆   ┆ u32       ┆ ---       ┆ u32       ┆ u32       │
│          ┆ u32       ┆ u32       ┆           ┆   ┆           ┆ u32       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0         ┆ 0         ┆ 1212946   ┆ … ┆ 0         ┆ 1212946   ┆ 1212946   ┆ 0         │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘